# packages in environment at /Users/zach.button/opt/anaconda3/envs/msda-test:
#
# Name                    Version                   Build  Channel
altair                    4.1.0                    pypi_0    pypi
appnope                   0.1.0                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
asn1crypto                1.3.0                    py37_0    conda-forge
astor                     0.8.1                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     20.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
base58                    2.0.1                    pypi_0    pypi
blas                      1.0                         mkl    conda-forge
bleach                    3.2.1                    pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
boto3                     1.15.10                    py_0  
botocore                  1.18.16            pyh9f0ad1d_0    conda-forge
ca-certificates           2020.7.22                     0  
cachetools                4.1.1                    pypi_0    pypi
cairo                     1.14.12              hc4e6be7_4  
cctools_osx-64            949.0.1              h5ba7a2e_7    conda-forge
certifi                   2020.6.20                py37_0  
cffi                      1.13.2           py37hb5b8e2f_0  
chardet                   3.0.4                    pypi_0    pypi
clang                     10.0.1          default_hf57f61e_1    conda-forge
clang_osx-64              10.0.1              h05bbb7f_10    conda-forge
clangxx                   10.0.1          default_hf57f61e_1    conda-forge
clangxx_osx-64            10.0.1              h05bbb7f_10    conda-forge
click                     7.1.2                    pypi_0    pypi
cmdstanpy                 0.9.5                    pypi_0    pypi
compiler-rt               10.0.1               he6db49b_0    conda-forge
compiler-rt_osx-64        10.0.1               h033240e_0    conda-forge
convertdate               2.2.2              pyh9f0ad1d_0    conda-forge
cryptography              2.8              py37ha12b0ac_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.21          py37hdadc0f0_0    conda-forge
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
docutils                  0.15.2                   py37_0    conda-forge
entrypoints               0.3                      pypi_0    pypi
enum-compat               0.0.3                    pypi_0    pypi
ephem                     3.7.7.1          py37h0b31af3_0    conda-forge
expat                     2.2.10               hb1e8313_2  
fbprophet                 0.7.1            py37hdadc0f0_0    conda-forge
fontconfig                2.13.0               h5d5b041_1  
freetds                   1.00.97              ha12b0ac_0  
freetype                  2.10.2               ha233b18_0  
fribidi                   1.0.10               haf1e3a3_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.63.1               hd977a24_0  
graphite2                 1.3.14               h38d11af_0  
graphviz                  2.40.1               hefbbd9a_2  
harfbuzz                  1.8.8                hb8d4a28_0  
holidays                  0.10.3             pyh9f0ad1d_0    conda-forge
icu                       58.2                 h0a44026_3  
idna                      2.8                      py37_0  
importlib-metadata        2.0.0                    pypi_0    pypi
intel-openmp              2019.4                      233  
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.18.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jmespath                  0.9.4                      py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9b                   he5867d9_2  
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
kiwisolver                1.2.0            py37h04f5b5a_0  
korean_lunar_calendar     0.2.1              pyh9f0ad1d_0    conda-forge
ld64_osx-64               530                  h3c32e8a_7    conda-forge
libclang-cpp10            10.0.1          default_hf57f61e_1    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libcxxabi                 4.0.1                hcfea43d_1    conda-forge
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libllvm10                 10.0.1               h009f743_3    conda-forge
libpng                    1.6.37               ha441bb4_0  
libtiff                   4.1.0                hcb84e12_0  
libxml2                   2.9.9                hf6e021a_1  
llvm-tools                10.0.1               h1341992_3    conda-forge
lunarcalendar             0.0.9                      py_0    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.2                         0    conda-forge
matplotlib-base           3.2.2            py37h5670ca0_0  
mistune                   0.8.4                    pypi_0    pypi
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.15           py37h5e564d8_0  
mkl_random                1.1.0            py37ha771720_0  
nbclient                  0.5.0                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1  
nest-asyncio              1.4.1                    pypi_0    pypi
notebook                  6.1.4                    pypi_0    pypi
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h6575580_1  
openssl                   1.1.1h               haf1e3a3_0    conda-forge
packaging                 20.4                     pypi_0    pypi
pandas                    1.1.2            py37hdadc0f0_0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
pango                     1.42.4               h7e27002_1  
parso                     0.7.1                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.44                 hb1e8313_0  
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0                    pypi_0    pypi
pip                       20.0.2                   py37_1    conda-forge
pixman                    0.40.0               haf1e3a3_0  
prometheus-client         0.8.0                    pypi_0    pypi
prompt-toolkit            3.0.7                    pypi_0    pypi
protobuf                  3.13.0                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pyarrow                   1.0.1                    pypi_0    pypi
pycparser                 2.19                     py37_0  
pydeck                    0.5.0b1                  pypi_0    pypi
pygments                  2.7.1                    pypi_0    pypi
pymeeus                   0.3.7              pyh9f0ad1d_0    conda-forge
pymssql                   2.1.4            py37h1de35cc_0  
pyodbc                    4.0.30           py37h0a44026_0  
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.7                      py_0  
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1                    py37_0    conda-forge
pystan                    2.19.1.1                 pypi_0    pypi
python                    3.7.6                h359304d_2  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyzmq                     19.0.2                   pypi_0    pypi
readline                  7.0                  h1de35cc_5  
requests                  2.24.0                   pypi_0    pypi
s3transfer                0.3.0                    py37_0    conda-forge
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                45.1.0                   py37_0    conda-forge
setuptools-git            1.2                      pypi_0    pypi
six                       1.14.0                   py37_0    conda-forge
sqlite                    3.30.1               ha441bb4_0  
streamlit                 0.68.0                   pypi_0    pypi
tapi                      1000.10.8            h879752b_4    conda-forge
terminado                 0.9.1                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0    conda-forge
toml                      0.10.1                   pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.50.0             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.4                    pypi_0    pypi
tzlocal                   2.1                      pypi_0    pypi
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.25.8                   py37_0  
validators                0.18.1                   pypi_0    pypi
watchdog                  0.10.3                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.34.1                   py37_0    conda-forge
widgetsnbextension        3.5.1                    pypi_0    pypi
xgboost                   1.2.0                    pypi_0    pypi
xz                        5.2.4                h1de35cc_4  
zipp                      3.3.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
